<a href="https://colab.research.google.com/github/Sharzzdevise/Python-for-machine-learning/blob/Master/Data_manipulation_practicals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dot product(multiplying both matrices together)

In [2]:
import numpy as np
import pandas as pd
np.random.seed(0)
mat_1 = np.random.randint(10,size=(5,3))
mat_2 = np.random.randint(10,size=(5,3))

mat_1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [3]:
mat_2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [4]:
mat_1.shape, mat_2.shape

((5, 3), (5, 3))

In [5]:
mat_1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [11]:
mat_1.shape, mat_2.T.shape #follow this format if you want to successfully carry out a dot operation

((5, 3), (3, 5))

In [14]:
mat_3 = np.dot(mat_1,mat_2.T) #dot product-multiplying both matrices together
mat_3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [20]:
#create a dataframe using random numbers for a reallife analysis
np.random.seed(0)
sales_data = np.random.randint(25,size=(5,3))
sales_data

array([[12, 15, 21],
       [ 0,  3,  3],
       [ 7,  9, 19],
       [21, 18,  4],
       [23,  6, 24]])

In [21]:
#create a weekly sales dataframe
weekly_sales = pd.DataFrame(sales_data,index=["Monday","Tuesday","Wednesday","Thursday","Friday"],
                            columns=["Sushi","Noodles","Tofu"])
weekly_sales

Sushi  Noodles  Tofu
Monday        12       15    21
Tuesday        0        3     3
Wednesday      7        9    19
Thursday      21       18     4
Friday        23        6    24

In [22]:
#create price array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [25]:
#create a dataframe for prices, and reshape
menu_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Sushi","Noodles","Tofu"])
menu_prices

Sushi  Noodles  Tofu
Price     10        8    12

In [26]:
#you can't use the dot function coz shapes aren't aligned, so we need to transpose first
total_sales = prices.dot(sales_data.T)
total_sales

array([492,  60, 370, 402, 566])

In [30]:
weekly_sales.shape, menu_prices.shape

((5, 3), (1, 3))

In [31]:
#Transpose weekly sales data
weekly_sales.T.shape

(3, 5)

In [32]:
#creating daily sales
daily_sales = menu_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [33]:
weekly_sales.shape

(5, 3)

In [35]:
weekly_sales

Sushi  Noodles  Tofu
Monday        12       15    21
Tuesday        0        3     3
Wednesday      7        9    19
Thursday      21       18     4
Friday        23        6    24

In [36]:
#transpose weekly sales by adding another column eg total
weekly_sales["total($)"] = daily_sales.T
weekly_sales

Sushi  Noodles  Tofu  total($)
Monday        12       15    21       492
Tuesday        0        3     3        60
Wednesday      7        9    19       370
Thursday      21       18     4       402
Friday        23        6    24       566

The above are data manipulations done with NumPy

Now, Pandas

In [56]:
#creating a series of car types
import pandas as pd
cars = pd.Series(["Toyota","Honda","Corolla","Ford","Sienna","Tom","Accord","Bora"])
cars

0     Toyota
1      Honda
2    Corolla
3       Ford
4     Sienna
5        Tom
6     Accord
7       Bora
dtype: object

In [57]:
colours = pd.Series(["Red","Green","Black","Grey","Brown","Silver","Ash","Blue"])
colours

0       Red
1     Green
2     Black
3      Grey
4     Brown
5    Silver
6       Ash
7      Blue
dtype: object

In [58]:
prize_usd = pd.Series([50000,10000,256000,89000,67000,435000,78000,767690])
prize_usd

0     50000
1     10000
2    256000
3     89000
4     67000
5    435000
6     78000
7    767690
dtype: int64

In [59]:
rating = pd.Series([5,4,5,4,3,4,5,4.5])
rating

0    5.0
1    4.0
2    5.0
3    4.0
4    3.0
5    4.0
6    5.0
7    4.5
dtype: float64

In [60]:
#creating a dataframe for cars and colours;by creating a dictionary; cartype is the key, cars is the value
car_data = pd.DataFrame({"car_type":cars,"colour":colours,"prize_usd":prize_usd,"rating":rating})
car_data

car_type  colour  prize_usd  rating
0   Toyota     Red      50000     5.0
1    Honda   Green      10000     4.0
2  Corolla   Black     256000     5.0
3     Ford    Grey      89000     4.0
4   Sienna   Brown      67000     3.0
5      Tom  Silver     435000     4.0
6   Accord     Ash      78000     5.0
7     Bora    Blue     767690     4.5

In [61]:
car_data.index

RangeIndex(start=0, stop=8, step=1)

In [66]:
car_data.describe()

prize_usd    rating
count       8.000000  8.000000
mean   219086.250000  4.312500
std    262192.038832  0.703943
min     10000.000000  3.000000
25%     62750.000000  4.000000
50%     83500.000000  4.250000
75%    300750.000000  5.000000
max    767690.000000  5.000000

In [67]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   car_type   8 non-null      object 
 1   colour     8 non-null      object 
 2   prize_usd  8 non-null      int64  
 3   rating     8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 384.0+ bytes


In [68]:
car_data.isnull()

car_type  colour  prize_usd  rating
0     False   False      False   False
1     False   False      False   False
2     False   False      False   False
3     False   False      False   False
4     False   False      False   False
5     False   False      False   False
6     False   False      False   False
7     False   False      False   False

In [69]:
#to know the lenght of your dataframe
len(car_data)

8

In [70]:
#.loc(.location) takes an integer as a series, and it chooses from your dataframe or series, whichever matches.
car_data.loc()

In [72]:
car_data.loc[4]

car_type     Sienna
colour        Brown
prize_usd     67000
rating          3.0
Name: 4, dtype: object

In [73]:
#iloc does same thing, the only difference is that it will bring out the exact same position.
car_data.iloc[4]

car_type     Sienna
colour        Brown
prize_usd     67000
rating          3.0
Name: 4, dtype: object

In [74]:
car_data.iloc()

In [76]:
#you can do slicing with .loc and .iloc
#get all the rows up to(and including) index 2
car_data.iloc[:5]

car_type colour  prize_usd  rating
0   Toyota    Red      50000     5.0
1    Honda  Green      10000     4.0
2  Corolla  Black     256000     5.0
3     Ford   Grey      89000     4.0
4   Sienna  Brown      67000     3.0

In [77]:
#use .loc when you are referring to indexes eg 0,1,2,3,4....
#use .iloc when you are referring to positions in the dataframe, where index is out of order
#also, if you want to select a column, you can call the column name

#select column
car_data['colour']

0       Red
1     Green
2     Black
3      Grey
4     Brown
5    Silver
6       Ash
7      Blue
Name: colour, dtype: object

Boolean indexing[<,>]works with columns too

In [ ]:
#Boolean use
car_data[car_data["prize_usd"] > 50000]

In [ ]:
#lower the colour column; prints them all in lower case
car_data['colour'].str.lower()

In [ ]:
#to select a particular set of items eg select cars made by Toyota
car_data[car_data["Make"] == "Toyota"]

In [ ]:
#compare car make with number of doors
pd.crosstab(car_data["Make"],car_data["colour"])

In [ ]:
#group by a column and find the mean
car_data.groupby(["prize_usd"]).mean()

In [ ]:
#how to drop a column
car_data = car_data.drop("ratings", axis = 1)
car_data