<a href="https://colab.research.google.com/github/Sharzzdevise/Python-for-machine-learning/blob/Master/Numpy_and_panda's_beauty.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import NumPy 
import numpy as np
arr = [2,3,4,5]
print(type(arr)) #print type

<class 'list'>


In [3]:
a = np.array(arr)
print(a)
print(type(a)) #
print(a.shape) #a is an ID array with 4 items
print(a.dtype)
print(a.ndim) #ndim; the number of dimensions of an array


[2 3 4 5]
<class 'numpy.ndarray'>
(4,)
int64
1


In [4]:
b = np.array([[1,2,3,4], [4,5,6,4]])
print(b)
print(type(b)) 
print(b.ndim)
print(b.shape)
print(b.dtype)

[[1 2 3 4]
 [4 5 6 4]]
<class 'numpy.ndarray'>
2
(2, 4)
int64


In [5]:
a = np.array(arr)
print(a)
print(type(a)) #
print(a.shape) #a is an ID array with 4 items
print(a.dtype)
print(a.ndim) #ndim; the number of dimensions of an array
b = np.array([[1,2,3,4], [4,5,6,4]])
print(b)
print(type(b)) 
print(b.ndim)
print(b.shape)
print(b.dtype)

[2 3 4 5]
<class 'numpy.ndarray'>
(4,)
int64
1
[[1 2 3 4]
 [4 5 6 4]]
<class 'numpy.ndarray'>
2
(2, 4)
int64


There are also some inbuilt functions that can be used to initialize numpy which include;

In [6]:
np.random.random((2,3)) #The random() method returns a random floating number between 0 and 1

array([[0.66909211, 0.22885286, 0.44347187],
       [0.40248386, 0.06984455, 0.27229441]])

In [7]:
np.zeros((2,3)) # returns a new array of given shape and type, where the element's value as 0.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,3)) #returns a new array of given shape and data type, where the element's value is set to 1. 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.identity((2)) #Return a identity matrix i.e. a square matrix with ones on the main diagonal.

array([[1., 0.],
       [0., 1.]])

In [10]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
c = np.array([[1,2,3,4,5], [6,7,8,9,0]]) 
d = np.array([[2,4,6,8,0], [1,3,5,7,9]])
print(c+d)
print(c * d)
print(c / d)
print (c - d)
print (c**2)

[[ 3  6  9 12  5]
 [ 7 10 13 16  9]]
[[ 2  8 18 32  0]
 [ 6 21 40 63  0]]
[[0.5        0.5        0.5        0.5               inf]
 [6.         2.33333333 1.6        1.28571429 0.        ]]
[[-1 -2 -3 -4  5]
 [ 5  4  3  2 -9]]
[[ 1  4  9 16 25]
 [36 49 64 81  0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


Panda

Series in pandas can be referred to as a one dimensional array with homogenous elements of different types somewhat similar to numpy arrays; however, it can be indexed differently with specified descriptive labels or integers.  

In [13]:
import pandas as pd
days = pd.Series(['monday', 'tuesday', 'wednesday', 'thursday', 'friday'])
print(days)

0       monday
1      tuesday
2    wednesday
3     thursday
4       friday
dtype: object


In [14]:
#creating series with a numpy array
days_list = np.array(['monday','tuesday','wednesday','thursday','friday'])
numpy_days = pd.Series(days_list)
print(numpy_days)

0       monday
1      tuesday
2    wednesday
3     thursday
4       friday
dtype: object


In [15]:
#using strings as index
days = pd.Series(['monday','tuesday','wednesday','thursday','friday'])
index = (['a','b','c','d','e'])

In [16]:
#creating series from a dictionary
days_1 = pd.Series({'a':'monday','b':'tuesday','c':'wednesday','d':'thursday','e':'friday'})
print(days_1)

a       monday
b      tuesday
c    wednesday
d     thursday
e       friday
dtype: object


In [17]:
days_1[0]

'monday'

In [18]:
days_1[4]

'friday'

In [19]:
days_1['d']

'thursday'

In [20]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [21]:
df_dict = {'Country':['Peru','China','India','Abidjan'],'Capital':['Slovak','Chile','Mumbai','Ivorycoast'],
           'Population':[200000,45000,60900,496000],'Age':[45,79,102,500]}
df = pd.DataFrame(df_dict, index=[1,2,3,4])
df_list = [['Peru','Slovak',200000,45],['China','Chile',45000,79],
           ['India','Mumbai',60900,102],['Abidjan','Ivorycoast',496000,500]]
df_1 =pd.DataFrame(df_list, columns=['Country','Capital','Population','Age'], index=[1,2,3,4])
print(df)

   Country     Capital  Population  Age
1     Peru      Slovak      200000   45
2    China       Chile       45000   79
3    India      Mumbai       60900  102
4  Abidjan  Ivorycoast      496000  500


In [22]:
df.iloc[3]

Country          Abidjan
Capital       Ivorycoast
Population        496000
Age                  500
Name: 4, dtype: object

In [23]:
df.loc[3]

Country        India
Capital       Mumbai
Population     60900
Age              102
Name: 3, dtype: object

In [24]:
df.at[2,'Country']

'China'

In [25]:
df.iat[1,0]

'China'

In [26]:
df['Capital']

1        Slovak
2         Chile
3        Mumbai
4    Ivorycoast
Name: Capital, dtype: object

In [27]:
df.describe()

Population        Age
count       4.000000    4.00000
mean   200475.000000  181.50000
std    208956.859583  213.62038
min     45000.000000   45.00000
25%     56925.000000   70.50000
50%    130450.000000   90.50000
75%    274000.000000  201.50000
max    496000.000000  500.00000

In [28]:
df['Population'].sum()

801900

In [29]:
df_dict2 = {'Name':['Sharon','Cindy','Wiz',np.nan,'Kess'],
        'Age':[23,25,45,66,np.nan],
        'Height':[196,np.nan,188,175,199]}
new_df = pd.DataFrame(df_dict2)
print(new_df)

     Name   Age  Height
0  Sharon  23.0   196.0
1   Cindy  25.0     NaN
2     Wiz  45.0   188.0
3     NaN  66.0   175.0
4    Kess   NaN   199.0


In [30]:
new_df.isnull() #check for missing values

Name    Age  Height
0  False  False   False
1  False  False    True
2  False  False   False
3   True  False   False
4  False   True   False

In [31]:
new_df.describe()

Age      Height
count   4.000000    4.000000
mean   39.750000  189.500000
std    20.122541   10.723805
min    23.000000  175.000000
25%    24.500000  184.750000
50%    35.000000  192.000000
75%    50.250000  196.750000
max    66.000000  199.000000

In [32]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    4 non-null      object 
 1   Age     4 non-null      float64
 2   Height  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 248.0+ bytes


In [33]:
new_df.dropna() #remove rows with missing values

Name   Age  Height
0  Sharon  23.0   196.0
2     Wiz  45.0   188.0

In [34]:
a1 = np.array([1,2,3,4]) #a 1 dimensional array is called a vector

In [35]:
a2 = np.array([[1,2,3,4],[5,6,7,8]]) #a 2 dimensional array is called a matrix

In [36]:
a3 = np.array([[1,2,3,4],[5,6,7,8],[9,1.0,1.1,1.2],[3,4,5,6],[7,8,9,0],[2,4,6,8]]) #a 3 dimensional array is also called a matrix

In [37]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((4,), 1, dtype('int64'), 4, numpy.ndarray)

In [38]:
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 4), 2, dtype('int64'), 8, numpy.ndarray)

In [39]:
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((6, 4), 2, dtype('float64'), 24, numpy.ndarray)

In [40]:
a3

array([[1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. ],
       [9. , 1. , 1.1, 1.2],
       [3. , 4. , 5. , 6. ],
       [7. , 8. , 9. , 0. ],
       [2. , 4. , 6. , 8. ]])

In [41]:
simple_array = np.array([1,2,3]) #creating an array
simple_array, simple_array.dtype

(array([1, 2, 3]), dtype('int64'))

In [42]:
ones = np.ones([4,3]) #creating a matrix of ones
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
zeros = np.zeros([5,3,3]) #creating a matrix of zeros
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
random_array = np.random.randint(10,size=(5,3)) #creating a random array; as you run it,it will keep generating random nos
random_array

array([[3, 6, 1],
       [4, 4, 7],
       [7, 7, 4],
       [9, 2, 5],
       [4, 4, 6]])

In [45]:
np.random.seed(0) #this code prevent reproduction of random nos in array at every run.
random_array = np.random.randint(10,size=(5,3))
random_array

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [46]:
np.random.seed(0)
import pandas as pd #creating a dataframe for the array
df = pd.DataFrame(np.random.randint(10,size=(5,3)))
df

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2
3  4  7  6
4  8  8  1

In [47]:
a1

array([1, 2, 3, 4])

In [48]:
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [49]:
a3

array([[1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. ],
       [9. , 1. , 1.1, 1.2],
       [3. , 4. , 5. , 6. ],
       [7. , 8. , 9. , 0. ],
       [2. , 4. , 6. , 8. ]])

In [50]:
a1[0]

1

In [51]:
a2[0]

array([1, 2, 3, 4])

In [52]:
a3[0]

array([1., 2., 3., 4.])

In [53]:
a2[1]

array([5, 6, 7, 8])

In [54]:
a3[:2,:2] #getting the first 2 values of the 2 rows of the array

array([[1., 2.],
       [5., 6.]])

In [55]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [56]:
a4.shape

(2, 3, 4, 5)

In [57]:
a1.sum()

10

In [58]:
a3.mean()

4.595833333333333

In [59]:
a3.max()

9.0

In [60]:
a3.std()

2.7517387180148885

In [61]:
a3.shape

(6, 4)

In [62]:
a3.min()

0.0

In [67]:
a2.shape

(2, 4)

In [73]:
#to be able to do a2 + a3 successfully, we need to reshape to same shape 
a2.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
#Transpose = switching the axis 
a2.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])